services:
  auth-frontend:
    restart: unless-stopped
    build:
      context: ./auth
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./auth:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_ORY_SDK_URL=https://auth-dev.with-jiko.com
      - LOG_LEVEL=debug
    extra_hosts:
      - "auth-dev.with-jiko.com:49.12.22.114"