FROM node:22

WORKDIR /app

COPY package*.json ./
COPY packages ./packages

RUN npm install

ENV NODE_ENV=development
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
ENV NEXT_TELEMETRY_DISABLED=1
ENV WATCHPACK_POLLING=true 
ENV CHOKIDAR_USEPOLLING=true

EXPOSE 3000

CMD ["npm", "run", "dev"]