services:
  frontend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    network_mode: host
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_ORY_SDK_URL=https://auth-dev.with-jiko.com
      - LOG_LEVEL=debug
    extra_hosts:
      - "auth-dev.with-jiko.com:49.12.22.114"